id: P98A970BF
initial_creation_type: input
source_metadata:
  title: Khenchen Ngawang Lodrö Rinchen
  language: fr
  description: 'Texts by Khenchen Ngawang Lodrö Rinchen (mkhan chen ngag dbang blo
    gros rin chen, 1892–1952):'
  volume:
    2d46ad1fb4194040bf96ee69bc01e8f2:
      title: Prayer for the Long Life of Kyabgön Sakya Trichen
      parent: Long Life Prayers
created_at: '2022-03-01T00:21:03.088261'
last_modified_at: '2022-03-01T00:21:03.088265'
